interface PPSection {
  title: string;
  content: string[];
  effectiveDate?: string;
}

export const ppContent: PPSection[] = [
  {
    title: "1. Introduction",
    content: [
      "At KenkoNav, we prioritize your privacy and are committed to ensuring transparency about how your information is handled. This Privacy Policy outlines our practices regarding the collection, use, and storage of data when you use our platform."
    ]
  },
  {
    title: "2. Data Collection",
    content: [
      "KenkoNav does not collect or store any personal or sensitive data provided by users.",
      "Any information you input into the platform, such as ingredient details, dietary restrictions, or allergies, is handled entirely on your device and is not transmitted to any external server."
    ]
  },
  {
    title: "3. Local Storage",
    content: [
      "The data you provide may be temporarily stored in the local storage of your browser to enhance your experience. This ensures the platform operates efficiently during your session.",
      "Local storage is managed by your browser and device, and KenkoNav has no access to this data."
    ]
  },
  {
    title: "4. No External Databases",
    content: [
      "KenkoNav does not maintain any external databases or servers to store user data.",
      "All data remains on the user's device, and no information is sent to or retained by KenkoNav."
    ]
  },
  {
    title: "5. Third-Party AI Models",
    content: [
      "KenkoNav utilizes the following AI models to provide its services:",
      "- Gemini Flash 1.5 by Google DeepMind for analyzing ingredient images.",
      "- Llama 3.1 by Meta for generating text-based responses.",
      "These models operate independently, and KenkoNav does not have control over how they process the data provided to them. For more details, refer to the respective privacy policies of Google DeepMind and Meta."
    ]
  },
  {
    title: "6. Data Security",
    content: [
      "Since KenkoNav does not collect or store user data, we are not responsible for securing data on your device or browser.",
      "Users are encouraged to take appropriate measures to protect their devices and browsers from unauthorized access or vulnerabilities."
    ]
  },
  {
    title: "7. Responsibility for Data",
    content: [
      "Any data theft or loss resulting from vulnerabilities in your device, browser, or internet connection is not the responsibility of KenkoNav.",
      "By using KenkoNav, you acknowledge that the data remains entirely under your control."
    ]
  },
  {
    title: "8. AI-Generated Insights",
    content: [
      "The insights provided by KenkoNav are generated by third-party AI models and are experimental in nature.",
      "KenkoNav does not validate or verify the accuracy of these insights and is not liable for any decisions made based on them."
    ]
  },
  {
    title: "9. Changes to the Privacy Policy",
    content: [
      "KenkoNav reserves the right to update this Privacy Policy at any time without prior notice.",
      "Users are encouraged to review this policy periodically to stay informed about how their data is handled."
    ]
  },
  {
    title: "10. Contact Information",
    content: [
      "If you have any questions or concerns regarding this Privacy Policy, please contact us at [Insert Contact Information].",
      "By using KenkoNav, you agree to this Privacy Policy. If you do not agree, please discontinue use of the platform immediately."
    ]
  }
];

// **Privacy Policy**

// **Effective Date:** 21 December 2024

// **1. Introduction**
// At KenkoNav, we prioritize your privacy and are committed to ensuring transparency about how your information is handled. This Privacy Policy outlines our practices regarding the collection, use, and storage of data when you use our platform.

// ---

// **2. Data Collection**
// - KenkoNav does not collect or store any personal or sensitive data provided by users.
// - Any information you input into the platform, such as ingredient details, dietary restrictions, or allergies, is handled entirely on your device and is not transmitted to any external server.

// ---

// **3. Local Storage**
// - The data you provide may be temporarily stored in the local storage of your browser to enhance your experience. This ensures the platform operates efficiently during your session.
// - Local storage is managed by your browser and device, and KenkoNav has no access to this data.

// ---

// **4. No External Databases**
// - KenkoNav does not maintain any external databases or servers to store user data.
// - All data remains on the user’s device, and no information is sent to or retained by KenkoNav.

// ---

// **5. Third-Party AI Models**
// - KenkoNav utilizes the following AI models to provide its services:
//   - **Gemini Flash 1.5** by Google DeepMind for analyzing ingredient images.
//   - **Llama 3.1** by Meta for generating text-based responses.
// - These models operate independently, and KenkoNav does not have control over how they process the data provided to them. For more details, refer to the respective privacy policies of Google DeepMind and Meta.

// ---

// **6. Data Security**
// - Since KenkoNav does not collect or store user data, we are not responsible for securing data on your device or browser.
// - Users are encouraged to take appropriate measures to protect their devices and browsers from unauthorized access or vulnerabilities.

// ---

// **7. Responsibility for Data**
// - Any data theft or loss resulting from vulnerabilities in your device, browser, or internet connection is not the responsibility of KenkoNav.
// - By using KenkoNav, you acknowledge that the data remains entirely under your control.

// ---

// **8. AI-Generated Insights**
// - The insights provided by KenkoNav are generated by third-party AI models and are experimental in nature.
// - KenkoNav does not validate or verify the accuracy of these insights and is not liable for any decisions made based on them.

// ---

// **9. Changes to the Privacy Policy**
// - KenkoNav reserves the right to update this Privacy Policy at any time without prior notice.
// - Users are encouraged to review this policy periodically to stay informed about how their data is handled.

// ---

// **10. Contact Information**
// If you have any questions or concerns regarding this Privacy Policy, please contact us at [Insert Contact Information].

// ---

// By using KenkoNav, you agree to this Privacy Policy. If you do not agree, please discontinue use of the platform immediately.

